### ISSUE TITLE
Show jsdoc build errors

### ISSUE THREAD

**Issue by fumbleforce** [fabienb4/meteor-jsdoc#1]
The build errors returned from the jsdoc command in build_docs.sh don't seem to be piped anywhere.
This resulted in data not being generated with no apparent way of knowing why my docs were empty.

Even when none of my comments were added, it printed "Docs successfully built".
I ran jsdoc manually to find the syntax errors in my documentation.

It would be useful to have these errors in the logfile, or simply displayed in the terminal.

Thanks for a great project though! Made me actually want to document my code for a change ;)

**Comment by fabienb4** [comment]
True, logs from the jsdoc command aren't shown anywhere.
The command used to build the docs is taken directly from the Meteor project, it's using grep to find the js files with comments and then pass them to the jsdoc command. It improves efficiency, but also do not return the logs.

When I have some time, I'll investigate the issue to find a way to get the logs to show up when an error occur with jsdoc.
If anyone wants to take a look at the problem, I'll gladly accept pull requests.
Here is the [command](https://github.com/fabienb4/meteor-jsdoc/blob/master/scripts/build_docs.sh#L9).

Thanks for the support! ;)

**Comment by Pushplaybang** [comment]
same problem, everything seems correct, but no dice.  just blank.

**Comment by Pushplaybang** [comment]
Nice.
