### ISSUE TITLE
Problem with `nodePath` on example

### ISSUE THREAD

**Issue by bySabi** [fabienb4/meteor-jsdoc#10]
First. 
Thanks!! .. your work is wonderful!
But you must remove this line:

```
...
  // node.js install path, default to: "/usr/bin/node"
  "nodePath": "/usr/bin/node",
...
```

from `jsdoc.json`
or advice on `README.md`
I install `node` from homebrew and here the path is `/usr/local/bin/node`. 
I think the script must check if `node` exist and fail is not. Right now fail without message.

**Comment by bySabi** [comment]
Actually I should add:

```
"nodePath": "/usr/local/bin/node",
```

to `jsdoc.json`

if I remove "nodePath" from `jsdoc.json`it not work cause this line on `config.js`
not work at all:

```
...
 jsdocJson.nodePath = execSync("which node").toString();
...
```

`execSync`return a `buffer` and I guest `toString()` include some special character not suitable for command line execution.

**Comment by fabienb4** [comment]
Thanks you for the support, it's very much appreciated.

Just updated so that the default config is now to use `which node`.
I don't want to remove the config in case people with multiple node installations want to use a specific one for meteor-jsdoc.

However `execSync` is working and `toString()` returns the output just fine for me.
PS: `execSync` is only available in node v0.12, if you have v0.10 it won't work.

**Comment by bySabi** [comment]
I was testing `execSync` on node 0.12.5 from `homebrew`

**Comment by bySabi** [comment]
I don´t know how inspect posible hidden characters on toString() output

**Comment by bySabi** [comment]
tested your PR ...

```
...
execSync("which node").toString().replace("\n", "");
...
```

Now work!! OK
Thanks @fabienb4

**Comment by fabienb4** [comment]
You're welcome. Weird that it didn't cause any trouble for me, but did for you though.

**Comment by bySabi** [comment]
Probably a shell issue, mine is `GNU bash, version 4.3.33`
Nevertheless now the code is more robust. This kind of hidden characters like "new line", by experience, can produce many difficult to find bugs.
Thanks again for your faster support. Now I need to write some code doc´s :-) :-)
