### ISSUE TITLE
Do I understand how this is supposed to work?

### ISSUE THREAD

**Issue by rjakobsson** [fabienb4/meteor-jsdoc#15]
Hi,
Say I have a project myProject1 which already includes docblocs in jsdoc style. 
Do I set up another project, myProject2 for the documentation server? Do I then run the `meteor-jsdoc init`command inside myProject1's project directory?

Actions per project: 
1. myProject1: meteor-jsdoc build
2. myProject1: meteor-jsdoc start
3. myProject2: meteor
4. the documentation for myProject1 is now available at myProject2

Have I understood it correctly?

**Comment by fabienb4** [comment]
You don't have to setup _myProject2_, only configure the config file in _myProject1_ which will be created after you run `meteor-jsdoc init` in _myProject1_.
_myProject2_ creation/setup will be done automatically when you build the docs according to the settings in `jsdoc.conf`:

```
myProject1: meteor-jsdoc init
myProject1: edit jsdoc.conf to use desired folder/settings
myProject1: meteor-jsdoc build
myProject1: meteor-jsdoc start
```

Open you browser and browse to http://localhost:`meteorPort` (setting in `jsdoc.conf`, default: 3333) to see the docs.

If you want to customize the way the docs look, you can go to the `docsPath` (setting in `jsdoc.conf`) folder. This is where the meteor app displaying the docs is located.
