### ISSUE TITLE
No errors. But no docs as well. :(

### ISSUE THREAD

**Issue by s7dhansh** [fabienb4/meteor-jsdoc#17]
I tried this with a small test project. Everything works perfectly. There is a data folder with the 2 jsons.

But when I use the exact same configuration in my project, nod docs are created. I copied the files from the test project folder to my project. Still no docs.

The problem is that I do not have much idea how to debug as the console output/logs do not have any errors.

I tried using jsdoc binary to create the docs, and it worked.

Can you tell me a few pointers on where to start looking? What info about my project would help you help me?

**Comment by fabienb4** [comment]
Please send me an email with a zip of your project (make sure you removed sensitive code if necessary), or at least screenshots of both folder structures & the content of the `jsdoc.json` file, and also the commands you used (in the order you used them), I'll try to help you.

PS: My email address is on my Github profile.
