### ISSUE TITLE
nothing added to the docs.

### ISSUE THREAD

**Issue by Pushplaybang** [fabienb4/meteor-jsdoc#2]
So I've followed your instructions to the letter, everything seems to make sense, got it to create a new meteor install in a seperate directory, copied over your example code for doc comments into server/main.js in my project but no dice.

Any ideas?

**Comment by Pushplaybang** [comment]
ps : all the commands seem to run without a hitch.  This looks like a really awesome project would love to get it working.

**Comment by fabienb4** [comment]
0.2.5 should fix your problem.

If not, the command now shows errors in the terminal, feel free to re-open.

**Comment by Pushplaybang** [comment]
Fantastic, I'll give it a go and report back if I still have issues.  cheers.

**Comment by Pushplaybang** [comment]
Hey updated, no errors on build, just says docs built successfully, its definitely creating the data folder  - but its empty, I'm using the comment example in your readme in my server/main.js file.  when I run it theres nothing added to the docs.... any ideas?

**Comment by fabienb4** [comment]
Is your config file setup right?
I specifically used the example from the readme to test if 0.2.5 solved the problem, and it does for me.

If it still doesn't work, send me a copy of your project & project docs folders, I'll see what I can do. My email address is on my profile.

**Comment by Pushplaybang** [comment]
so super fail on my part

I didn't have jsdoc installed.

all I needed was `npm install -g jsdoc`

and everything is sweet.  Thanks for the awesome package.

**Comment by fabienb4** [comment]
Fixed in 0.3.0, the path for local jsdoc is now retrieved automatically.

**Comment by Pushplaybang** [comment]
nice.
