### ISSUE TITLE
coffescript documentation not working

### ISSUE THREAD

**Issue by edulix** [fabienb4/meteor-jsdoc#20]
Coffeescript support doesn't seem to work. When I execute `meteor-jsdoc build`, I get `main.coffee: Line 1: Unexpected token ILLEGAL` for a file whose content is something like

``` coffee
###
@summary foobar
###
```

how to add coffeescript support? is there any example?

**Comment by fabienb4** [comment]
JSDoc doesn't support coffeescript.

See: 
https://github.com/jsdoc3/jsdoc/issues/915#issuecomment-73538702

https://stackoverflow.com/questions/28380732/is-it-possible-to-use-jsdoc-on-coffeescript-files-without-compiling-them
