### ISSUE TITLE
Fails silently upon syntax errors?

### ISSUE THREAD

**Issue by rune-bk** [fabienb4/meteor-jsdoc#21]
I noticed during some documentation where a sentence or other form of multi-symbol was left within {}, the docs fail to build.

Should be reproducible with this:

``` javascript
/**
   * @memberOf Meteor.methods
   * @locus Server
   * @summary Adds a period to the contract
   * @param {String} contractID
   * @param {Object} period - {from: unixTimestamp, to: unixTimestamp}
   */
```

This would no longer update the docs on build. It will state a successful build, but I can't find any logs stating where the error is? I have apparently done this now with something else, and I can't for the life of me find out what or where.

If you have documented several files of functions and encounter an error such as this, you have no idea where to look and you have to backtrack your documentation to find the culprit. Exceptionally time consuming!

**Comment by fabienb4** [comment]
Ehm, I just tried your code and it works for me. The docs build properly:

![screenshot_2015-10-21_13-49-30](https://cloud.githubusercontent.com/assets/8208974/10648288/bd6c74f8-77fa-11e5-898b-da79607db8e9.png)

However, if you want to follow Meteor's way of commenting, you might want to do that:

``` js
 /**
   * @memberOf Meteor.methods
   * @locus Server
   * @summary Adds a period to the contract
   * @param {String} contractID
   * @param {Object} period
   * @param {UnixTimestamp} period.from
   * @param {UnixTimestamp} period.to
   */
```

It will give you this (this is what I implemented in the latest version):

![screenshot_2015-10-21_13-53-25](https://cloud.githubusercontent.com/assets/8208974/10648376/452119f8-77fb-11e5-8663-f1ce8b058385.png)

If you are still having troubles, don't hesitate to send me an email with your source code, I will try to figure it out. (Email on my profile page)

**Comment by rune-bk** [comment]
Found another which had me looking a while. I misunderstood the @namespace tag

``` javascript
/**
 * @summary Utility namespace globally available server side. Mostly used for filemanagement and cronjobs
 * @namespace CompanyServer
 * @locus Server
 */
CompanyServer = {
...
```

Removing "CompanyServer" from @namespace line allowed it to build again. It would be useful with some kind of log to indicate at least the comment bracket it fails?

However, it seems to successfully build on occation with the same syntax error?

``` javascript
/**
 * @summary Meteor methods are run server side, and callable from client
 * @example Meteor.call("methodName", param1, param2...);
 * @locus Server
 * @namespace Meteor.methods
 *
 */
Meteor.methods({
...
```

Runs absolutely fine

**Comment by fabienb4** [comment]
Both work for me.
And both should: [JSDoc @namespace](http://usejsdoc.org/tags-namespace.html)

Any error produced by bad comments should be outputted to the console.
Here is an error example if you were to write `@param {[Object]}` instead of `@param {Object[]}`:

```
ERROR: Unable to parse a tag's type expression for source file test.js with tag title "param" and text "{[Object]} period": Invalid type expression "[Object]"...
```

**Comment by rune-bk** [comment]
Then I find it very weird that it doesn't always rebuild. The build is always successful but it does not refresh the meteor instance. The files seem unaltered. Fixing what appeared to be the bug triggers a correct rebuild. I did some testing with exclude to find the bugged files. 

The build itself was always ok, but it didn't refresh, until I excluded the files that needed editing and rebuilt without them. Re-added them and edited them, it rebuilt perfectly. Only things I changed are mentioned above. No errors anywhere that I'm able to find. 

Had it been an open source project I'd happily share, but this is for a client so I am not at liberty to disclose the code. I was trying out this as a documenting solution for the project in case someone continues development later. Besides these strange quirks it seems very good!

**Comment by fabienb4** [comment]
Well, I did look at the log to confirm that the Meteor instance was properly refreshed after a build with your code (both examples), and it is.
In the docs folder, you should have an `app.log` file, there you can find the logs of the Meteor instance, and see if it is refreshing or not.
Have you checked the browser's console on the docs server, maybe it is throwing an error there?

You might have some piece of code somewhere that is making meteor-jsdoc bug somehow... It might not be due to the comments themselves.

Keep me posted on your findings, you might have an edge case difficult to reproduce, if so, it would be nice to be able to fix it.
