### ISSUE TITLE
Adding markdown files to documentation blocks

### ISSUE THREAD

**Issue by fumbleforce** [fabienb4/meteor-jsdoc#24]
In order to look more like the meteor docs and allow more flexible documentation, it should be able to add markdown files to a documentation block, like shown below.
![selection_005](https://cloud.githubusercontent.com/assets/1506286/11095188/10ae0722-8894-11e5-9d5f-822a80fff0d7.png)

**I have already done the work** in my fork, so I was wondering whether or not this is something that is wanted :)

**Comment by fumbleforce** [comment]
Great work @fabienb4 ! Made it a lot easier to add short markdown snippets before and after. However, it still won't allow me to include markdown **files**, which is very useful when providing large examples or  explaining a lot of theory (which I have in my app).

Having documentation like below [Meteor.publish(name, func)](http://docs.meteor.com/#/full/publishandsubscribe)  inline would be very cumbersome, because it is so big. I would much rather have a **.md** file alongside it.

Proposal for how this can be done, if you find the idea appealing. https://github.com/fabienb4/meteor-jsdoc/compare/master...jorgeer:master

**Comment by fabienb4** [comment]
Thanks @jorgeer.

I created an issue specifically for your problem, explaining my thoughts, let's see what others think. I will also tackle the problem. See #26.
