### ISSUE TITLE
preamble.md location?

### ISSUE THREAD

**Issue by chiroptical** [fabienb4/meteor-jsdoc#25]
Hey @fabienb4, I am a bit confused as to where my custom `preamble.md` is supposed to be located. Is it supposed to be copied into the documentation directory? Or, in the same directory as `jsdoc.json`?

Awesome tool by the way!

**Comment by fabienb4** [comment]
Hi. The file is created for you in `<docsPath>/client/templates`, just modify it as you see fit. See [Readme](https://github.com/fabienb4/meteor-jsdoc#preamble).

If you want to take a look at an advanced configuration, see the [Turkserver project](https://github.com/HarvardEconCS/turkserver-meteor) maintained by @mizzao. You have a good example of a configuration, including:
- custom `preamble.md`.
- `<docsPath>` as a subfolder of the actual meteor project with proper `jsdoc-conf.json`.
- proper `.gitignore` for customized templates.

Thanks for the support, always appreciated. :+1:

**Comment by chiroptical** [comment]
I understand, the "skipping" message is for the preamble.md inside the documentation. Thanks!

**Comment by fabienb4** [comment]
Yes, to avoid overwriting changes you may have made to it, after it's creation, it won't be copied again in the docs.
