### ISSUE TITLE
Can't see any docs

### ISSUE THREAD

**Issue by derwaldgeist** [fabienb4/meteor-jsdoc#27]
I've tried meteor-jsdoc with both a custom project and the example project shipped with it. In both cases, I am able to start the server, but the documentation does not include anything (besides a header, an empty API navigation area, and a "show all types" checkbox).

I don't get any errors, neither on the console nor in the app. Tried it on a Mac under Yosemite, with the out-of-the-box configuration (nothing changed in the json files). I also tried to call the meteor server directly instead of starting it with meteor-jsdoc start. It runs without any errors, but still no docs. The app.log file is also clean:

```
[[[[[ ~/myproject-docs ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3333/
```

The client/data folder is empty.

Any ideas what may go wrong here?

**Comment by fabienb4** [comment]
Do you have anything in the `<docsPath>/client/data/` folder? You should have 2 files `docs-names.js` and `docs-data.js`.

I never tested the code on Mac OS (I don't have Mac devices). There might me an OS specific problem somewhere, somehow...
If anyone has tested `meteor-jsdoc` on Mac OS, it would be nice to get your feedback.

**Comment by derwaldgeist** [comment]
No, the data folder is empty.

**Comment by fabienb4** [comment]
Can you try again with latest 0.10.0 version and report back please?

**Comment by fabienb4** [comment]
I'll close this, if you are still having problems, feel free to reopen!
