### ISSUE TITLE
Document all the things

### ISSUE THREAD

**Issue by Pushplaybang** [fabienb4/meteor-jsdoc#3]
Hey There

So I've got this working for my methods, and please excuse my ignorance not used JSDOC before, but I'd like to know, how would go about documenting something like a schema from simpleschema?   and is it at all possible add in arbitrary blocks?

**Comment by fabienb4** [comment]
Well, that's up to you and what you want to comment...

The basic way to do it would be: 

``` js
/**
 * @summary Schema describing an Item.
 * @locus Anywhere
 * @type {SimpleSchema}
 */
Schemas.Item = new SimpleSchema({

});
```

Any comment with a `@summary` will be included in the docs. Any comment without a `@summary` won't.
It allows to exclude comments from the docs, but still have them in the source.

You can find many examples going through meteor source. No schema though.

Please send me an email if you have any question (on my profile). Trying to keep issues issues.
