### ISSUE TITLE
escaping problem for the build command on Windows

### ISSUE THREAD

**Issue by croustibat65** [fabienb4/meteor-jsdoc#33]
Hi, I'm new to npm, I just had to install it just to get meteor-jsdoc.
When I follow the tutorial, I get troubles with all the paths of the command.
In debug mode it does the following:

> DEBUG: config =  {
>  "debug": true,
>  "nodePath": "C:\nodejs\node.exe",
>  "docsPath": "../projecthw-doc",
>  "meteorPort": 3333,
>  "initMeteor": true,
>  "updateMeteor": true,
>  "preamble": true,
>  "projectRepo": "https://github.com/username/myproject/tree/master",
>  "docsConfig": {
>    "title": "projecthw",
>    "metas": {
>      "description": "My description"
>    }
>  }
> }
> Meteor initialized.  
> Skipped 'preamble.md' copy to avoid overwritting.  
> DEBUG: Build cmd:  C:nodejsnode.exe C:UsersmyusernameAppDataRoamingnpmnode_modulesmeteor-jsdocnode_modules.binjsdoc --debug -t C:UsermyusernameAppDataRoamingnpmnode_modulesmeteor-jsdoctempl[...]
> xargs: C:nodejsnode.exe: No such file or directory
> Docs successfully built.

What's the problem?

**Comment by croustibat65** [comment]
And despite the "docs successfully built", nothing in the data folder.
I would love to get it to work!

**Comment by fabienb4** [comment]
I can't test it on Windows... But as far as I can tell, there might be a problem with the command executed when building the docs. I'll take a look.
Windows support is still not that great, and has not been the primary focus to be honest. I'll work on that!

**Comment by croustibat65** [comment]
Thanks a lot, that project looks amazing!
At worst, I could make it work inside a VM

**Comment by fabienb4** [comment]
Can you give the new v0.20.0 a try and report back to me @croustibat65?

**Comment by croustibat65** [comment]
Wow that was quick :)
Apprently the escaping problem disappeared, but a new one came up:

> PS C:\dev\myproject> meteor-jsdoc build
> 
> ## meteor-jsdoc: Automated JSDoc generation for Meteor projects
> 
> DEBUG: config = {
>  "debug": true,
> 
>  "nodePath": "C:\nodejs\node.exe",
>  "docsPath": "C:\dev\myproject-doc",
>  "meteorPort": 3333,
>  "initMeteor": true,
>  "updateMeteor": true,
>  "preamble": true,
>  "projectRepo": "https://github.com/username///tree/master",
>  "docsConfig": {
>    "title": "Meteor Project Docs",
>    "metas": {
>      "description": "Documentation for a meteor project."
>    }
>  }
> }
> Meteor initialized.
> Skipped preamble.md copy to avoid overwritting.
> DEBUG: "C:\nodejs\node.exe C:\Users\myuser\AppData\Roaming\npm\node_modules\meteor-jsdoc\node_modules\.bin\jsdoc --debug -t C:\Users\myuser\AppData\
> Roaming\npm\node_modules\meteor-jsdoc\template -c C:\dev\myproject\jsdoc-conf.json -d C:\dev\myproject-doc "
> :\Users\myuser\AppData\Roaming\npm\node_modules\meteor-jsdoc\node_modules.bin\jsdoc:4
> ase `uname` in
> ^^^
> 
> yntaxError: Unexpected token case
>    at exports.runInThisContext (vm.js:53:16)
>    at Module._compile (module.js:374:25)
>    at Object.Module._extensions..js (module.js:417:10)
>    at Module.load (module.js:344:32)
>    at Function.Module._load (module.js:301:12)
>    at Function.Module.runMain (module.js:442:10)
>    at startup (node.js:136:18)
>    at node.js:966:3
> 
> Docs built with errors.

But I tried on an existing project, I'll give a try on the meteor simple todo, to see if it's not coming from a problem inside my repo.

**Comment by fabienb4** [comment]
I installed a Windows VM just for you @croustibat65! Haha!

So, I tested it, and it should now work properly, and even allow spaces in paths (damn Windows spaces).

**Comment by croustibat65** [comment]
Thanks!
That's one of the main problems with Windows I agree!
Ok, now, I should get my documentation done, I guess...
