### ISSUE TITLE
can\t connect mongo?

### ISSUE THREAD

**Issue by Pushplaybang** [fabienb4/meteor-jsdoc#4]
I've created a project in my ~ dir, had this working previously, haven't used it for a while and now when trying to startup get nothing in chrome.  if I try to start the meteor docs app directly I get the following error message.  any ideas?

```
Unexpected mongo exit code 100. Restarting.   
Can't start Mongo server.                     
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.
```

**Comment by fabienb4** [comment]
Looks like something's wrong with MongoDB... Try shutting down the docs app, then deleting the `.meteor/local` folder and restarting the docs app. If it doesn't do the trick, something went wrong on your computer. Try deleting the docs, and rebuilding then.

**Comment by fabienb4** [comment]
If you have more troubles, can you please provide more information. Otherwise can you close the issue?

**Comment by Pushplaybang** [comment]
Sure thing, just saw this now, will give ir another try and report back, thanks for your response.

Paul:)

**Comment by Pushplaybang** [comment]
yeah deleting it seems to have been the trick.  I had tried just setting init to true but it needed to be totally removed and recreated.

**Comment by fabienb4** [comment]
@Pushplaybang Perfect, I'm closing the issue then.

`init: true` only overwrite the meteor files. `.meteor/local` is created when the app starts, it contains the built app and mongoDB files. It probably got messed up somehow, and deleting it forces the app to recreate it when changes are made.
