### ISSUE TITLE
Not working on windows.

### ISSUE THREAD

**Issue by bhuvnesh91** [fabienb4/meteor-jsdoc#40]
Root cause that I figured out ,its running jsdoc instead of jsdoc.cmd for windows, so that dirname command(used in jsdoc sh) is not working which results in '.' and failed to get ../jsdoc/jsdoc.js

**Comment by fabienb4** [comment]
This is probably due to find, xargs, or grep missing from your system.
1.0.3 should now fail if a command is missing, and I added a note in the README for Windows users, who need to have git bash with Unix tools installed for it to work properly.

**Comment by bhuvnesh91** [comment]
Thanks
