### ISSUE TITLE
Examples of JSDoc syntax used in Meteor

### ISSUE THREAD

**Issue by mizzao** [fabienb4/meteor-jsdoc#44]
I found this link that seems to have been written by MDG:

> https://meteor.hackpad.com/Automatically-Generating-API-Docs-using-JSDoc-EpPmd2iuFEH

It seems that it might be useful to link to it for two reasons.
- it provides a few examples of documentation that were used on the Meteor API
- it may be a helpful reference for features this package has missed

Just curious, was that document used to develop this? Or was it conceived completely independently?

**Comment by fabienb4** [comment]
Hey @mizzao 

Thanks for the link.
No, I actually used the source code to figure it out (the initial script was part of meteor repo, I built on it).

If you see any missing features, fell free to open an issue, or better yet, a pull request! ;-)
