### ISSUE TITLE
Error logging

### ISSUE THREAD

**Issue by radik** [fabienb4/meteor-jsdoc#7]
It would be nice, if you add logging facility. For example, when you write documentation with error:

```
@summary My Func with wrong doc.
@param {[String]} wrongDocumentedArgType - Argument type should be {String[]}
```

meteor-jsdoc informs that "Docs successfully built." which is not true.

**Comment by mizzao** [comment]
I think this would be helpful too. Right now all errors go to `/dev/null` when running `meteor-jsdoc build` and it would be good to print out whatever errors jsdoc is complaining about.

Thanks!
