### ISSUE TITLE
Support for helpers, Typescript, Coffeescript, ES6, etc?

### ISSUE THREAD

**Issue by mizzao** [fabienb4/meteor-jsdoc#8]
This looks great! I'm very glad I found it before I rolled my own.

Does this support generating docs from files other than just JS? What about auto-documenting helpers that packages provide?

If this is already supported, sorry for asking a question as an issue. If not, I'd be happy to contribute to make it happen.

**Comment by fabienb4** [comment]
The package is using jsdoc to create the documentation, so it has the same capabilities as jsdoc.
See https://github.com/jsdoc3/jsdoc

It basically reproduces what Meteor.com docs look like with some additional features. The script that creates the docs is actually the same that MDG uses to generate the docs for the Meteor project.

**Comment by mizzao** [comment]
Thanks - very helpful; I also figured that out here: https://forums.meteor.com/t/documentation-generator-for-meteor-apps/5476/5

What would be your recommended way of generating a preamble like `docs.meteor.com` has before the main API, automatically from a package (without having to edit the output)?

**Comment by fabienb4** [comment]
Right now, the preamble would need to be edited in the meteor server of the docs. But I'm sure we can come up with a better way to handle it. Like outputting a `.md` file from the project as the preamble for the docs.

And BTW, if you see any feature that would be useful, and you want to contribute, I'd be happy to review the changes you propose.

**Comment by mizzao** [comment]
Great! As you can see, I've written a lot of Meteor packages and would love to contribute.

**Comment by mizzao** [comment]
I'm trying to use this with the ES6 transpilers right now. What would be the right way to configure the processing file extensions besides `.js`?

According to https://github.com/meteor/babel/issues/3 we will need to have `.jsx` or `.es6` extensions at the moment. So how to pick up those files as well?

**Comment by fabienb4** [comment]
`git grep` won't get in the way and will get all types of files with `@summary` comments.
But you would have to change the `jsdoc-conf.json` to include a custom `source.includePattern`.
See: http://usejsdoc.org/about-configuring-jsdoc.html

Default is: 

``` js
".+\\.js(doc)?$"
```

> Only files ending in ".js" and ".jsdoc" will be processed (source.includePattern);

**Comment by mizzao** [comment]
Hmm. Would it be possible to read this setting from `jsdoc.json` or are you saying I need to fork the package and also edit `jsdoc-conf.json`?

**Comment by mizzao** [comment]
Holy shit, that was fast. I was just about to fork your project and do that myself, but serious props that you did that as I was just poking around.

**Comment by fabienb4** [comment]
I just did a quick commit, this should allow you to do what you want. `jsdoc-conf.json` file is now copied in the project when using `meteor-jsdoc init`.

**Comment by mizzao** [comment]
Yep, just installed 0.3.2 - thanks!

**Comment by fabienb4** [comment]
Preamble support is pretty basic, but it gets the job done and it's dead simple to use...

**Comment by mizzao** [comment]
I see. I have a pretty extensive preamble for my docs at https://github.com/HarvardEconCS/turkserver-meteor/tree/master/docs, so maybe we could figure out how to generalize that in some way. I basically edited the template that `meteor-jsdoc` generates with some other code that automatically organizes markdown templates into sections.

If you have time to take a look, let me know what you think. I'd be happy to help make an API of some sort for using this in a Meteor app.

**Comment by fabienb4** [comment]
How about something like this @mizzao?
It allows for complete & cleaner control of the output, and markdown support for ease-of-use...
It's a single file to edit, and the navbar is updated automatically according to the content of the md file.

**Comment by mizzao** [comment]
Thanks a lot. That looks pretty badass in terms of features, I would love to convert my app over to use that.

Things have been pretty busy of late, and when I get a moment I'd just like to take some time to compare this implementation to what I am already using and see if anything can be added!

**Comment by fabienb4** [comment]
You're welcome!

To convert, you pretty much only have to copy the content of all your templates in `docs.html` into the `preamble.md` file, and use template names as titles [#-######] so that you get a link in the sidebar.
Everything should look almost the same after that.

If you see any feature that could be added, let me know, my email is on my profile!

**Comment by mizzao** [comment]
Excellent, just tried and it looks f**king fantastic. Nested headers and everything! 

The only comment I have would be that I put a GitHub ribbon on the docs and need to change the meta information, so I have to override the contents of the `<head>` and `<body>` tags. One way to work around this would be to programmatically render the `{{> docs}}` template into the body (like how routers do it) instead of with the template file. But that's just a minor nitpick.

The only differences in my files now are these: https://github.com/HarvardEconCS/turkserver-meteor/tree/master/docs

**Comment by gbhatnag** [comment]
I'm using CoffeeScript for my Meteor application.  Does meteor-jsdoc support CoffeeScript?  I've added docs into my code with the following format:

```
###
# @summary Comments are added to posts for discussion purposes.
# ...
###
```

When building and starting the meteor-jsdoc server, I do not see anything appear on the API Docs page...

Any tips for getting this to work with CoffeeScript?

**Comment by fabienb4** [comment]
Take a look at [specifying-input-files](http://usejsdoc.org/about-configuring-jsdoc.html#specifying-input-files).
I'm guessing that is your problem, you need to edit the `source.includePattern` so that jsdoc is including `.coffee` files when looking for comments. You declare that in the `jsdoc-conf.json` file which is project specific (created in your project folder when init command is ran).

PS: For questions (anything BUT spam...), you can send me emails instead of using issues. ;-)

**Comment by fabienb4** [comment]
@gbhatnag see #20
