### ISSUE TITLE
Silent failure if `nodePath` is not specified

### ISSUE THREAD

**Issue by mizzao** [fabienb4/meteor-jsdoc#9]
Just spent an hour trying to figure this out, wondering why nothing was showing up. Meteor generation works, but `client/data` is created but empty.

Seems like if `nodePath` is not specified, we should just try to use `node` on the commandline.

**Comment by fabienb4** [comment]
Just updated.
I made it so that `which node` is used to determine where node is installed if `nodePath` isn't specified.

**Comment by mizzao** [comment]
Great, thanks very much!
